jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install AWS
          command: |
            apk add --update --no-cache curl jq python3 py-pip
            pip3 install -q --upgrade --no-cache-dir awscli
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_REGISTRY_URL/niyohn/tuner:$CIRCLE_SHA1 .
            echo $(aws ecr get-authorization-token --region $AWS_REGION --output text --query 'authorizationData[].authorizationToken'     | base64 -d | cut -d: -f2) | docker login -u AWS $DOCKER_REGISTRY_URL --password-stdin
            docker push $DOCKER_REGISTRY_URL/niyohn/tuner:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: aws
