version: 2.1
docker-registry-url: &docker_registry_url 645001498044.dkr.ecr.eu-north-1.amazonaws.com/niyohn
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_REGISTRY_URL/tuner:$CIRCLE_SHA1 .
            docker push $DOCKER_REGISTRY_URL/tuner:latest
